<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class EvaluationSeeder extends Seeder
{
  public function run()
  {
    // Disable foreign key checks
    Schema::disableForeignKeyConstraints();

    // Users
    DB::table('users')->truncate();
    \App\Models\User::create([
      'name' => 'Admin',
      'email' => 'admin@test.com',
      'password' => bcrypt('password'),
      'is_admin' => true,
    ]);

    // Categories
    DB::table('categories')->truncate();
    DB::table('categories')->insert([
      array(
        'id' => 1,
        'name' => 'Laptop',
        'slug' => 'laptop',
        'description' => 'High-performance laptops for gaming, work, and everyday use',
        'parent_id' => NULL,
        'is_active' => 1,
        'sort_order' => 1,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:45:08',
      ),
      array(
        'id' => 2,
        'name' => 'Desktop PCs',
        'slug' => 'desktop-pcs',
        'description' => 'Custom built and pre-built desktop computers',
        'parent_id' => NULL,
        'is_active' => 1,
        'sort_order' => 2,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:45:08',
      ),
      array(
        'id' => 3,
        'name' => 'Graphics Cards',
        'slug' => 'graphics-cards',
        'description' => 'Latest NVIDIA and AMD graphics cards for gaming and professional work',
        'parent_id' => NULL,
        'is_active' => 1,
        'sort_order' => 3,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:45:08',
      ),
      array(
        'id' => 4,
        'name' => 'Processors',
        'slug' => 'processors',
        'description' => 'Intel and AMD processors for all performance levels',
        'parent_id' => NULL,
        'is_active' => 1,
        'sort_order' => 0,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:45:08',
      ),
      array(
        'id' => 5,
        'name' => 'Storage Devices',
        'slug' => 'storage-devices',
        'description' => 'SSDs, HDDs, and NVMe drives for all your storage needs',
        'parent_id' => NULL,
        'is_active' => 1,
        'sort_order' => 4,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:45:08',
      ),
      array(
        'id' => 6,
        'name' => 'Monitors',
        'slug' => 'monitors',
        'description' => 'Gaming and professional monitors in various sizes and resolutions',
        'parent_id' => NULL,
        'is_active' => 1,
        'sort_order' => 5,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:45:08',
      ),
      array(
        'id' => 7,
        'name' => 'Gaming Accessories',
        'slug' => 'gaming-accessories',
        'description' => 'Keyboards, mice, headsets, and more for gamers',
        'parent_id' => NULL,
        'is_active' => 1,
        'sort_order' => 6,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:45:08',
      ),
    ]);

    // Products
    DB::table('products')->truncate();
    DB::table('products')->insert([
      array(
        'id' => 1,
        'category_id' => 7,
        'name' => 'HP Omen 16 Gaming Laptop - DarkGreen - Updated',
        'slug' => 'hp-omen-16-gaming-laptop-darkgreen-9223',
        'sku' => 'SKU-AWI-6989',
        'description' => 'Aut est quasi hic totam deserunt. Explicabo qui pariatur nesciunt id ad. At unde fuga qui. Voluptatem quas magnam consequuntur nostrum sint.',
        'specifications' => '{"Brand":"Bernhard-Bernhard","Model":"xj-6215","Warranty":"1 Year","Color":"Thistle"}',
        'price' => '14263.06',
        'old_price' => '17400.93',
        'stock' => 73,
        'is_active' => 1,
        'is_featured' => 1,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 281,
        'rating' => '4.14',
        'reviews_count' => 290,
        'sort_order' => 0,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 2,
        'category_id' => 4,
        'name' => 'Razer BlackWidow V4 Pro Mechanical Keyboard - Turquoise',
        'slug' => 'razer-blackwidow-v4-pro-mechanical-keyboard-turquoise-4081',
        'sku' => 'SKU-SAU-2786',
        'description' => 'Dolorem veniam qui dolor nostrum. Ut voluptatum aut quo minus eos. Aut sint nihil corrupti qui sit error sint.',
        'specifications' => '{"Brand":"Ruecker, Hills and Willms","Model":"al-6107","Warranty":"1 Year","Color":"Orange"}',
        'price' => '405311.73',
        'old_price' => NULL,
        'stock' => 84,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 1,
        'is_flash_deal' => 0,
        'views' => 268,
        'rating' => '3.87',
        'reviews_count' => 94,
        'sort_order' => 11,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 18:38:19',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 3,
        'category_id' => 2,
        'name' => 'Razer BlackWidow V4 Pro Mechanical Keyboard - Yellow',
        'slug' => 'razer-blackwidow-v4-pro-mechanical-keyboard-yellow-1153',
        'sku' => 'SKU-FID-8278',
        'description' => 'Maiores totam porro in blanditiis consequatur harum perferendis. Et magni iusto cupiditate sapiente. Iure laudantium necessitatibus harum earum aut corporis. Ex aut autem ratione possimus earum totam.',
        'specifications' => '{"Brand":"Williamson-Harris","Model":"ax-1347","Warranty":"3 Years","Color":"SandyBrown"}',
        'price' => '63453.07',
        'old_price' => '91372.42',
        'stock' => 37,
        'is_active' => 1,
        'is_featured' => 1,
        'is_new' => 1,
        'is_flash_deal' => 0,
        'views' => 53,
        'rating' => '4.87',
        'reviews_count' => 352,
        'sort_order' => 12,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 18:38:19',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 4,
        'category_id' => 1,
        'name' => 'LG UltraGear 27" 4K Gaming Monitor - Crimson',
        'slug' => 'lg-ultragear-27-4k-gaming-monitor-crimson-4343',
        'sku' => 'SKU-IWX-4966',
        'description' => 'Ut architecto nihil ut nam ut. Maiores eveniet dolore veritatis ratione veritatis blanditiis corrupti. Voluptates quod doloribus voluptatibus at aut vitae rerum. Ullam eius veniam explicabo dolorem. Expedita aut dignissimos labore amet earum assumenda.',
        'specifications' => '{"Brand":"Cartwright, Stokes and Gutkowski","Model":"vt-2537","Warranty":"1 Year","Color":"MediumOrchid"}',
        'price' => '112365.75',
        'old_price' => '125849.64',
        'stock' => 91,
        'is_active' => 1,
        'is_featured' => 1,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 450,
        'rating' => '3.99',
        'reviews_count' => 398,
        'sort_order' => 13,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 18:38:19',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 5,
        'category_id' => 6,
        'name' => 'WD Black SN850X 4TB NVMe SSD - LightPink',
        'slug' => 'wd-black-sn850x-4tb-nvme-ssd-lightpink-7078',
        'sku' => 'SKU-GDR-0554',
        'description' => 'Id quo quam aliquam qui fugiat ipsam inventore. Voluptas dolorem aut et sequi. Rem veritatis qui eius.',
        'specifications' => '{"Brand":"Bartell-Raynor","Model":"dh-1140","Warranty":"3 Years","Color":"DodgerBlue"}',
        'price' => '92145.91',
        'old_price' => NULL,
        'stock' => 6,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 980,
        'rating' => '3.85',
        'reviews_count' => 76,
        'sort_order' => 14,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 18:38:19',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 6,
        'category_id' => 5,
        'name' => 'MSI MAG B760 Tomahawk WiFi Motherboard - Snow',
        'slug' => 'msi-mag-b760-tomahawk-wifi-motherboard-snow-6840',
        'sku' => 'SKU-OXY-2293',
        'description' => 'Et non deleniti aspernatur laudantium quis omnis ipsum ipsa. Pariatur voluptatem incidunt iure illum qui et cum. Temporibus eum officiis beatae.',
        'specifications' => '{"Brand":"Jakubowski-Grady","Model":"ce-9429","Warranty":"2 Years","Color":"LightYellow"}',
        'price' => '300041.02',
        'old_price' => NULL,
        'stock' => 82,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 185,
        'rating' => '3.92',
        'reviews_count' => 410,
        'sort_order' => 5,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 7,
        'category_id' => 7,
        'name' => 'Logitech G Pro X Superlight Wireless Mouse - LightCoral',
        'slug' => 'logitech-g-pro-x-superlight-wireless-mouse-lightcoral-6864',
        'sku' => 'SKU-CGG-3574',
        'description' => 'Amet iusto dolorem autem fugit possimus. Inventore atque non ipsum et. Suscipit necessitatibus velit voluptatem et sunt ipsa quos.',
        'specifications' => '{"Brand":"Abshire Ltd","Model":"ut-5371","Warranty":"1 Year","Color":"LightGray"}',
        'price' => '19054.96',
        'old_price' => NULL,
        'stock' => 96,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 521,
        'rating' => '3.58',
        'reviews_count' => 213,
        'sort_order' => 7,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 8,
        'category_id' => 5,
        'name' => 'LG UltraGear 27" 4K Gaming Monitor - Cyan',
        'slug' => 'lg-ultragear-27-4k-gaming-monitor-cyan-2473',
        'sku' => 'SKU-ZUV-7285',
        'description' => 'Nisi qui labore dolor et debitis aspernatur iure. Eos repudiandae saepe dolor. Tenetur voluptas quibusdam rerum alias et.',
        'specifications' => '{"Brand":"Medhurst Ltd","Model":"yg-4809","Warranty":"1 Year","Color":"Turquoise"}',
        'price' => '334565.16',
        'old_price' => NULL,
        'stock' => 85,
        'is_active' => 1,
        'is_featured' => 1,
        'is_new' => 1,
        'is_flash_deal' => 1,
        'views' => 789,
        'rating' => '4.91',
        'reviews_count' => 170,
        'sort_order' => 9,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 9,
        'category_id' => 1,
        'name' => 'Corsair RM1000x 1000W PSU - DarkMagenta',
        'slug' => 'corsair-rm1000x-1000w-psu-darkmagenta-9832',
        'sku' => 'SKU-BJJ-5056',
        'description' => 'Reprehenderit magni neque eveniet quis necessitatibus earum. Iusto fuga id ea sed dolor. Minus et quae possimus.',
        'specifications' => '{"Brand":"Little, Sipes and Pouros","Model":"fx-6251","Warranty":"3 Years","Color":"MediumPurple"}',
        'price' => '83132.09',
        'old_price' => NULL,
        'stock' => 71,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 1,
        'is_flash_deal' => 0,
        'views' => 763,
        'rating' => '4.96',
        'reviews_count' => 202,
        'sort_order' => 11,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 10,
        'category_id' => 5,
        'name' => 'NZXT Kraken Z73 RGB AIO Cooler - OliveDrab',
        'slug' => 'nzxt-kraken-z73-rgb-aio-cooler-olivedrab-9172',
        'sku' => 'SKU-UJX-0078',
        'description' => 'Aut consectetur id ex facere. Voluptas nisi doloribus cum corporis sunt eum nihil culpa. Iusto officia eos illum esse. Esse molestiae et necessitatibus quidem.',
        'specifications' => '{"Brand":"Haag PLC","Model":"nx-6134","Warranty":"2 Years","Color":"MediumAquaMarine"}',
        'price' => '257191.20',
        'old_price' => NULL,
        'stock' => 76,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 112,
        'rating' => '4.79',
        'reviews_count' => 249,
        'sort_order' => 13,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 11,
        'category_id' => 3,
        'name' => 'WD Black SN850X 4TB NVMe SSD - Pink',
        'slug' => 'wd-black-sn850x-4tb-nvme-ssd-pink-9533',
        'sku' => 'SKU-GAC-4347',
        'description' => 'Et dicta qui dolorem et at accusantium. Odit voluptatem qui velit pariatur nam earum aspernatur. Perferendis qui molestias repellat voluptas cumque nihil est.',
        'specifications' => '{"Brand":"Kuhlman, Gislason and Schmeler","Model":"mu-8862","Warranty":"1 Year","Color":"MediumSlateBlue"}',
        'price' => '425971.02',
        'old_price' => '558022.04',
        'stock' => 19,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 297,
        'rating' => '4.44',
        'reviews_count' => 55,
        'sort_order' => 10,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 18:22:16',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 12,
        'category_id' => 3,
        'name' => 'LG UltraGear 27" 4K Gaming Monitor - BlueViolet',
        'slug' => 'lg-ultragear-27-4k-gaming-monitor-blueviolet-4996',
        'sku' => 'SKU-OXE-3156',
        'description' => 'Eius voluptatum quo harum dignissimos non voluptatem. Quo minus voluptatum est iste itaque sed sint. Maiores id rerum consequatur aliquid autem. Perspiciatis iure sit libero fugiat nisi ut non error.',
        'specifications' => '{"Brand":"Crooks-Stanton","Model":"gm-9667","Warranty":"1 Year","Color":"SaddleBrown"}',
        'price' => '408183.93',
        'old_price' => NULL,
        'stock' => 46,
        'is_active' => 1,
        'is_featured' => 1,
        'is_new' => 0,
        'is_flash_deal' => 1,
        'views' => 72,
        'rating' => '3.57',
        'reviews_count' => 129,
        'sort_order' => 11,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 18:22:16',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 13,
        'category_id' => 3,
        'name' => 'HP Omen 16 Gaming Laptop - LightSkyBlue',
        'slug' => 'hp-omen-16-gaming-laptop-lightskyblue-4055',
        'sku' => 'SKU-XMN-6118',
        'description' => 'At quibusdam sed ut. Minima et sit exercitationem omnis est. Facere pariatur voluptas eligendi. Tempora eos laboriosam consectetur quos repudiandae et quae.',
        'specifications' => '{"Brand":"Becker, Hane and Zieme","Model":"rm-6367","Warranty":"2 Years","Color":"DarkRed"}',
        'price' => '251658.84',
        'old_price' => '354838.96',
        'stock' => 51,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 742,
        'rating' => '3.62',
        'reviews_count' => 283,
        'sort_order' => 12,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 18:22:16',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 14,
        'category_id' => 2,
        'name' => 'Corsair RM1000x 1000W PSU - DarkMagenta',
        'slug' => 'corsair-rm1000x-1000w-psu-darkmagenta-5469',
        'sku' => 'SKU-IWF-1498',
        'description' => 'Nihil suscipit officiis sunt enim. Et itaque adipisci asperiores molestiae. Vel qui et quae facere accusantium consequatur delectus.',
        'specifications' => '{"Brand":"Nader PLC","Model":"cy-5608","Warranty":"1 Year","Color":"Cyan"}',
        'price' => '478232.15',
        'old_price' => NULL,
        'stock' => 91,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 1,
        'is_flash_deal' => 0,
        'views' => 182,
        'rating' => '3.71',
        'reviews_count' => 285,
        'sort_order' => 13,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 18:22:16',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 15,
        'category_id' => 6,
        'name' => 'MSI MAG B760 Tomahawk WiFi Motherboard - MediumVioletRed',
        'slug' => 'msi-mag-b760-tomahawk-wifi-motherboard-mediumvioletred-4484',
        'sku' => 'SKU-WSE-5514',
        'description' => 'Doloribus minus in placeat rem aliquid est recusandae. Voluptatem est quisquam illo consequatur. Dolores asperiores officiis sint necessitatibus voluptates voluptas eos. Qui et nisi quas non.',
        'specifications' => '{"Brand":"West-Lueilwitz","Model":"ka-6545","Warranty":"3 Years","Color":"Ivory"}',
        'price' => '302852.55',
        'old_price' => '411879.47',
        'stock' => 34,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 1,
        'views' => 332,
        'rating' => '3.92',
        'reviews_count' => 420,
        'sort_order' => 14,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 18:22:16',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 16,
        'category_id' => 7,
        'name' => 'Samsung 990 PRO 2TB NVMe SSD - DimGrey',
        'slug' => 'samsung-990-pro-2tb-nvme-ssd-dimgrey-4938',
        'sku' => 'SKU-ISP-1297',
        'description' => 'Veniam necessitatibus nihil debitis ut. Similique omnis eaque amet ea. Voluptas laborum eveniet ut. Dolore neque quis et debitis ad.',
        'specifications' => '{"Brand":"Hammes, Cartwright and Blanda","Model":"ck-4789","Warranty":"3 Years","Color":"MediumSeaGreen"}',
        'price' => '85443.32',
        'old_price' => '115348.48',
        'stock' => 26,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 771,
        'rating' => '3.70',
        'reviews_count' => 417,
        'sort_order' => 1,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:44:44',
        'deleted_at' => '2025-12-12 19:44:44',
      ),
      array(
        'id' => 17,
        'category_id' => 3,
        'name' => 'MSI MAG B760 Tomahawk WiFi Motherboard - DarkGreen',
        'slug' => 'msi-mag-b760-tomahawk-wifi-motherboard-darkgreen-7917',
        'sku' => 'SKU-MTX-5495',
        'description' => 'Saepe repellat quis corporis. Neque eius architecto non eum et vel sit.',
        'specifications' => '{"Brand":"Emard-Jaskolski","Model":"ue-9957","Warranty":"1 Year","Color":"BurlyWood"}',
        'price' => '65016.38',
        'old_price' => NULL,
        'stock' => 16,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 59,
        'rating' => '4.36',
        'reviews_count' => 76,
        'sort_order' => 2,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 18,
        'category_id' => 5,
        'name' => 'NZXT Kraken Z73 RGB AIO Cooler - MistyRose',
        'slug' => 'nzxt-kraken-z73-rgb-aio-cooler-mistyrose-5285',
        'sku' => 'SKU-OMQ-2886',
        'description' => 'Harum dolores labore debitis eos. Enim illum sunt similique sequi. Sequi vitae provident incidunt culpa aperiam corporis.',
        'specifications' => '{"Brand":"White, Abshire and Christiansen","Model":"hx-4534","Warranty":"2 Years","Color":"NavajoWhite"}',
        'price' => '354779.81',
        'old_price' => NULL,
        'stock' => 18,
        'is_active' => 1,
        'is_featured' => 1,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 15,
        'rating' => '4.92',
        'reviews_count' => 285,
        'sort_order' => 3,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 19,
        'category_id' => 2,
        'name' => 'Sony WH-1000XM5 Wireless Headphones - LawnGreen',
        'slug' => 'sony-wh-1000xm5-wireless-headphones-lawngreen-5943',
        'sku' => 'SKU-FHC-4205',
        'description' => 'Distinctio rerum non ut et sint voluptatibus. Sint blanditiis quia modi qui quo. Voluptas labore quaerat ea architecto. Error veniam omnis rerum distinctio vel ex.',
        'specifications' => '{"Brand":"Fritsch, Blanda and Johnston","Model":"vi-2122","Warranty":"2 Years","Color":"DarkMagenta"}',
        'price' => '328480.32',
        'old_price' => NULL,
        'stock' => 55,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 121,
        'rating' => '3.61',
        'reviews_count' => 413,
        'sort_order' => 4,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 20,
        'category_id' => 6,
        'name' => 'Samsung 990 PRO 2TB NVMe SSD - DarkCyan',
        'slug' => 'samsung-990-pro-2tb-nvme-ssd-darkcyan-9078',
        'sku' => 'SKU-RGJ-9728',
        'description' => 'Ullam facilis qui qui veniam recusandae. Quo in quibusdam mollitia soluta totam. Rerum sed architecto mollitia itaque temporibus. Veniam repudiandae blanditiis nesciunt nesciunt.',
        'specifications' => '{"Brand":"Rogahn-Balistreri","Model":"dp-2326","Warranty":"3 Years","Color":"DarkOliveGreen"}',
        'price' => '424721.25',
        'old_price' => NULL,
        'stock' => 62,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 465,
        'rating' => '4.35',
        'reviews_count' => 127,
        'sort_order' => 6,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:44:50',
        'deleted_at' => '2025-12-12 19:44:50',
      ),
      array(
        'id' => 21,
        'category_id' => 1,
        'name' => 'NZXT Kraken Z73 RGB AIO Cooler - OrangeRed',
        'slug' => 'nzxt-kraken-z73-rgb-aio-cooler-orangered-3206',
        'sku' => 'SKU-RKN-8411',
        'description' => 'Fugiat ut accusamus sint natus. Labore laboriosam doloribus sequi aut optio soluta sunt. Laborum illum esse temporibus et omnis nulla non dolor. Soluta reprehenderit ducimus temporibus ut ipsam.',
        'specifications' => '{"Brand":"Von-Runte","Model":"tc-7801","Warranty":"2 Years","Color":"PapayaWhip"}',
        'price' => '123307.38',
        'old_price' => NULL,
        'stock' => 64,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 375,
        'rating' => '4.07',
        'reviews_count' => 249,
        'sort_order' => 8,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 22,
        'category_id' => 7,
        'name' => 'Sony WH-1000XM5 Wireless Headphones - CornflowerBlue',
        'slug' => 'sony-wh-1000xm5-wireless-headphones-cornflowerblue-9386',
        'sku' => 'SKU-OSA-6697',
        'description' => 'Ut quam natus nihil aut quo. Quo quia maxime dolore quaerat ratione omnis. Eligendi maiores magni dolor perspiciatis qui et.',
        'specifications' => '{"Brand":"Bailey-Nolan","Model":"tl-2299","Warranty":"1 Year","Color":"Brown"}',
        'price' => '154473.10',
        'old_price' => NULL,
        'stock' => 60,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 0,
        'is_flash_deal' => 1,
        'views' => 814,
        'rating' => '4.68',
        'reviews_count' => 487,
        'sort_order' => 10,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 23,
        'category_id' => 6,
        'name' => 'Sony WH-1000XM5 Wireless Headphones - ForestGreen',
        'slug' => 'sony-wh-1000xm5-wireless-headphones-forestgreen-2975',
        'sku' => 'SKU-FHI-6534',
        'description' => 'Et nulla temporibus quibusdam quo ab quo ducimus. Id quo cum rem dolor culpa dolorem. Voluptatem eum et tenetur sit omnis et quia voluptatem. Molestias voluptatibus deserunt soluta ut assumenda aut.',
        'specifications' => '{"Brand":"Romaguera-DuBuque","Model":"nh-7043","Warranty":"3 Years","Color":"LightSkyBlue"}',
        'price' => '264316.93',
        'old_price' => '333039.33',
        'stock' => 97,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 1,
        'is_flash_deal' => 0,
        'views' => 745,
        'rating' => '4.63',
        'reviews_count' => 344,
        'sort_order' => 12,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 24,
        'category_id' => 7,
        'name' => 'Dell XPS 15 Laptop - Azure',
        'slug' => 'dell-xps-15-laptop-azure-9280',
        'sku' => 'SKU-VGG-3357',
        'description' => 'Vel omnis quo culpa voluptas vel laborum. Debitis aspernatur minus et iste omnis. Quos aliquam labore unde unde.',
        'specifications' => '{"Brand":"Wehner-Trantow","Model":"hr-8394","Warranty":"2 Years","Color":"LimeGreen"}',
        'price' => '154146.61',
        'old_price' => NULL,
        'stock' => 48,
        'is_active' => 1,
        'is_featured' => 0,
        'is_new' => 1,
        'is_flash_deal' => 0,
        'views' => 433,
        'rating' => '3.75',
        'reviews_count' => 195,
        'sort_order' => 14,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 19:36:05',
        'deleted_at' => NULL,
      ),
      array(
        'id' => 25,
        'category_id' => 1,
        'name' => 'Samsung Galaxy Buds 3 FE - SlateBlue',
        'slug' => 'samsung-galaxy-buds-3-fe-slateblue-8517',
        'sku' => 'SKU-KPB-1182',
        'description' => 'Accusamus dolores explicabo ratione quia accusamus ut consequatur sit. Laudantium aut sapiente non vel. Debitis dolore harum rerum distinctio eum molestiae. Similique eius excepturi est iusto voluptatem et totam. Quia magni quisquam dolorem eius.',
        'specifications' => '{"Brand":"Grady, Bartell and Conn","Model":"dm-6011","Warranty":"2 Years","Color":"Gainsboro"}',
        'price' => '61911.92',
        'old_price' => '88534.05',
        'stock' => 66,
        'is_active' => 1,
        'is_featured' => 1,
        'is_new' => 0,
        'is_flash_deal' => 0,
        'views' => 818,
        'rating' => '4.71',
        'reviews_count' => 305,
        'sort_order' => 10,
        'created_at' => '2025-12-08 19:25:36',
        'updated_at' => '2025-12-12 18:38:19',
        'deleted_at' => NULL,
      ),
    ]);

    // Product Images
    DB::table('product_images')->truncate();
    DB::table('product_images')->insert([
      array(
        'id' => 1,
        'product_id' => 1,
        'image_path' => 'products/1765561100_693c530c46649.webp',
        'thumbnail_path' => NULL,
        'is_primary' => 1,
        'sort_order' => 1,
        'created_at' => '2025-12-12 17:38:20',
        'updated_at' => '2025-12-12 17:38:22',
      ),
      array(
        'id' => 2,
        'product_id' => 2,
        'image_path' => 'products/1765561630_693c551e6277b.webp',
        'thumbnail_path' => NULL,
        'is_primary' => 0,
        'sort_order' => 1,
        'created_at' => '2025-12-12 17:47:10',
        'updated_at' => '2025-12-12 17:47:10',
      ),
    ]);

    // Enable foreign key checks
    Schema::enableForeignKeyConstraints();
  }
}
